---
- hosts: "{{ tgt_node | default('k3snodes') }}"
  gather_facts: false
  any_errors_fatal: false 

  tasks:
    - name: Check Access to the Internet
      command: nslookup dns9.quad9.net
      register: stat_ns

    - name: Update cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: apt upgrade
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes  
    
    - name: APT Install 
      apt:
        name: ['net-tools']
        state: latest
      when: stat_ns.rc == 0
