---
- hosts: k3snodes
  any_errors_fatal: false 
  tasks:
    - name: Run the equivalent of "apt update" 
      apt:
        update_cache: yes

    - name: Update all packages to the latest version 
      apt:
        upgrade: dist

    - name: Remove useless packages from the cache 
      apt:
        autoclean: yes

    - name: Remove dependencies that are no longer required 
      apt:
        autoremove: yes

    - name: Reboot
      shell: sleep 10 && /sbin/shutdown -r now
      args:
          removes: /var/run/reboot-required
      async: 300
      poll: 0
      ignore_errors: true

    - name: Wait
      wait_for_connection:
          delay: 60
          timeout: 300

    - name: Verify
      command: uname -mrs
      register: uname_result

    - name: Display new kernel
      debug:
          var: uname_result.stdout lines
