---
- hosts: "{{ tgt_node | default('k3snodes') }}"
  gather_facts: false
  any_errors_fatal: false 
  tasks:
    - name: Update hostnames
      hostname:
        name: "{{ new_hostname }}"

    - include_tasks: /home/ubuntu/ansible/set_datetime.yml

    - name: Install node-hash-sum
      apt:
        name: ['net-tools']
        state: latest

    - name: Reboot if required
      command: shutdown -r now 'Rebooting...'
      args:
        removes: /var/reboot-required


