---
- hosts: "{{ localhost | default('k3snodes') }}"
  any_errors_fatal: false 
  tasks:
    - name: Ansible fact - ansible_date_time
      debug:
        var: ansible_date_time

    - name: Ansible fact - ansible_date_time.iso8601
      debug:
        msg: "Timestampt in the ISO8601 format: {{ ansible_date_time.iso8601 }}"
