---
- hosts: "{{ tgt_node | default('k3snodes') }}" 
  any_errors_fatal: false 
  tasks:
    - name: Gather package facts
      package_facts:
        manager: apt

    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: true
      register: apt_output
      when: '"docker.io" not in ansible_facts.packages'

    - debug: var=apt_output

    - name: Reboot if required
      command: shutdown -r now 'Rebooting...'
      args:
        removes: /var/reboot-required

    - name: Check if daemon.json already exists
      stat: path=/home/ubuntu/joink8s.sh
      register: stat_joink8s

    - name: Create joink8s.sh 
      copy:
        dest: "/home/ubuntu/joink8s.sh"
        content: |
          kubeadm join 10.0.1.110:6443 --token 0bltg1.lmqqwtlrqh2hl7wb --discovery-token-ca-cert-hash sha256:c0150d94620c30c8d09600113d3847a194eb96b5fc264d771a63417dd1c21007
      when: stat_joink8s.stat.exists == false          

    - name: Grant execute permission to joink8s.sh
      file:
        path: /home/ubuntu/joink8s.sh
        owner: root
        group: root
        mode: u+x 
      when: stat_joink8s.stat.exists == false

    - name: Verify docker is started
      command: systemctl status docker
      register: docker_status

      #- debug:
      #  msg: "{{ docker_status.rc }}"

    - name: Start docker
      service: 
        name: docker 
        state: restarted
        enabled: yes
      when: docker_status.stdout == "" and docker_status.rc != 0

    - name: Join the node to the cluster
      command: sh /home/ubuntu/joink8s.sh
