---
- hosts: "{{ tgt_node | default('k3snodes') }}" 
  any_errors_fatal: false 
  tasks:
    - name: Generate join command
      command: kubeadm token create --print-join-command
      register: join_command

    - name: Copy join command to local file
      local_action: copy content="{{ join_command.stdout_lines[0] }}" dest="./join-command"

    - name: Reboot if required
      command: shutdown -r now 'Rebooting...' 
      args:
        removes: /var/reboot-required
