---
- hosts: "{{ localhost | default('k3snodes') }}"
  any_errors_fatal: false 
  tasks:
    - name: Get date time fact
      debug: var=ansible_date_time.tz

    - name: Set timezone
      timezone: name=America/Chicago
      become: yes
      tags:
       - time
