---
- hosts: "{{ var_hosts | default('k3snodes') }}"
  gather_facts: false
  tasks:

    - name: Check if pubkey already exists
      stat: 
        path: "{{ id_rsa_file }}"
      register: stat_pub_key

    - name: Generating SSH key pair
      command: ssh-keygen -t rsa -b 4096 -f "{{ id_rsa_file }}" -q -N "{{ passphrase }}"
      when: stat_pub_key.stat.exists == false  

    - debug:
        msg: "Key pair already exists. Using the existing pubkey."
      when: stat_pub_key.stat.exists

    - name: Copy public key to the nodes
      command: sshpass -p "{{ root_password }}" ssh-copy-id -i "{{ id_rsa_file }}" "{{ user_id }}"@"{{ item }}" -f -o StrictHostKeyChecking=no
      with_items:
        - "{{ nodes }}"
          
  vars_files:
    - config.yml
