---
#
- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: all 
  #connection: local
  #ignore_unreachable: true
  any_errors_fatal: false 
  gather_facts: false
  remote_user: ubuntu

  tasks:
    - name: Test connection to instance
      ping:

