- name: Store known hosts of 'all' the hosts in the inventory file
  hosts: localhost
  connection: local
  any_errors_fatal: false
  gather_facts: false
  vars:
    ssh_known_hosts: "{{ k3snodes }}" 

  tasks:
  - debug:
      msg: "{{ item }} is alive"
    when: hostsvars[item].ansible_host is defined
    with_items: "{{ ssh_known_hosts }}"
